% Matlab Commands used in Lecture on Vibration Experiment for MAE175A students
% Adopted for data collected from WaveForm application during laboratory experiments
% R.A. de Callafon, Dept. of MAE, UCSD, 2011-2025

% Matlab Commands Similar to (3) on slide 57 of the lecture notes:
w1=2*pi*15;
w2=2*pi*8;
w3=2*pi*25;
beta1=0.01;
beta2=0.01;
beta3=0.01;
K=1;
num=[1 2*beta1*w1 w1^2];
den=conv([1 2*beta2*w2 w2^2],[1 2*beta1*w3 w3^2]);
Hij=K*w2^2*w3^2/w1^2*tf(num,den);

% Partial Matlab Commands similar to (4) on slide 58 of the lecture notes:
myf=logspace(0,2,500);
[m,p]=bode(Hij,2*pi*myf);

% Modified Matlab Commands similar to (6) on slide 68 of the lecture notes:
figure(1)
subplot(2,1,1)
semilogx(myf,20*log10(abs(squeeze(m))),'r')
ylabel('mag [dB]');
legend('amplitude response of model')
title('Bode plot of modelled frequency response from floor 1 to 2')
subplot(2,1,2);
semilogx(myf,squeeze(p),'r')
ylabel('angle [deg]');
legend('phase response of model')
xlabel('f [Hz]');


% Read data from a CSV file generated by WaveForm application
filename = 'sine_sweep01_floor1_and_floor2.csv';
if exist(filename)==0,
    disp(['Could no find CSV file ''' filename '''!']) 
    error('Perform measurements and save CSV file from WaveForm application')
end
M = csvread(filename,21,0);
f = M(:,1);
G = M(:,3);
P = M(:,4);

% Modified Matlab Commands similar to (6) on slide 68 of the lecture notes:
figure(1)
subplot(2,1,1)
semilogx(myf,20*log10(abs(squeeze(m))),'r',f,G,'b')
ylabel('mag [dB]');
legend('amplitude response of model','measured amplitude response')
title('Bode plot of modelled and measured frequency response from floor 1 to 2')
subplot(2,1,2);
semilogx(myf,squeeze(p),'r',f,P,'b')
ylabel('angle [deg]');
legend('phase response of model','measured phase response')
xlabel('f [Hz]');



